services:
    online_store_web:
        container_name: online_store_web
        image: nginx:alpine  # Use the Nginx image
        ports:
            - "8000:80"  # Map port 8080 on the host to port 80 inside the container
        volumes:
            - ./:/var/www  # Mount the Laravel application directory
            - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Use our Nginx config
        depends_on:
            - online_store_app  # Ensure PHP-FPM is started before Nginx
        networks:
            - online_store-network  # Connect to the custom network

    online_store_app:
        container_name: online_store_app
        build: .  # Build from the Dockerfile
        depends_on:
            - online_store_db
        volumes:
            - ./:/var/www  # Mount the Laravel application directory
        networks:
            - online_store-network  # Connect to the custom network

    online_store_db:
        container_name: online_store_db
        image: mysql:8  # Use MySQL image
        restart: always
        ports:
            - "3305:3306"
        environment:
            MYSQL_DATABASE: rent_app  # Create a database named 'laravel'
            MYSQL_ROOT_PASSWORD: root  # Set the root password for MySQL
        volumes:
            - online_store_db:/var/lib/mysql  # Persist MySQL data
        networks:
            - online_store-network  # Connect to the custom network

    online_store_node:
        container_name: online_store_node
        image: node:20
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - online_store-network
        command: bash -c "npm install && npm run build"
# Define the custom network
networks:
    online_store-network:  # Create a custom network named 'online_store-network'
        driver: bridge

# Define the volume for MySQL data persistence
volumes:
    online_store_db:
